//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wangkanai.Analytics.Internal {
    using System;
    using System.Diagnostics;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    public static class UniversalStrings {

        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Wangkanai.Analytics.Properties.UniversalStrings", typeof(UniversalStrings).GetTypeInfo().Assembly);


        public static string ArgumentIsEmpty(object argumentName)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("ArgumentIsEmpty", "argumentName"), argumentName);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            Debug.Assert(value != null);

            if (formatterNames != null)
                for (var i = 0; i < formatterNames.Length; i++)               
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");                            

            return value;
        }
    }
}
